### ISSUE TITLE
Undefined Variable causes Helm Template Failure

### ISSUE THREAD

**Issue by alex1989hu** [CrunchyData/postgres-operator-examples#65]
Due to undefined variable check introduced in https://github.com/CrunchyData/postgres-operator-examples/pull/64 the Helm Chart is broken.

Let me copy what I commented to the PR:

```sh
helm template . --debug
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /home/alex/other/postgres-operator-examples/helm/install


Error: template: pgo/templates/manager.yaml:23:23: executing "pgo/templates/manager.yaml" at <eq .Values.debug false>: error calling eq: incompatible types for comparison
helm.go:88: [debug] template: pgo/templates/manager.yaml:23:23: executing "pgo/templates/manager.yaml" at <eq .Values.debug false>: error calling eq: incompatible types for comparison
```

**Comment by jkatz** [comment]
What version of Helm are you using?

I did not reproduce this while testing.

**Comment by alex1989hu** [comment]
> What version of Helm are you using?
> 
> I did not reproduce this while testing.

It is [Helm 3.7.1](https://github.com/helm/helm/releases/tag/v3.7.1):

```sh
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
$ uname -a
Linux ubimachine 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jkatz** [comment]
I used similar. However to avoid confusion and/or other issues, I reverted it in 538c3c3.
